### PR TITLE
fix: remove wrong argument in integer asString operator

### LINKED ISSUE #1823: Radon operator IntegerAsString not working
Captura de pantalla de 2022-10-26 10-55-34

The IntegerAsString operator has an integer argument in sheikah, which seems invalid. It is not possible to remove that argument, and I did not find any way to pass a valid argument there.

### PR DESCRIPTION
**Pull request by Tommytrg**
This fixes https://github.com/witnet/sheikah/issues/1823
image

### CODE REVIEW

File: src/structures.ts [hunk 1]
```diff
@@ -421,11 +421,12 @@ export const operatorInfos: OperatorInfos = {
...
-        name: 'base',
-        optional: true,
-        type: MirArgumentType.Integer,
-      },
+      // This argument isn't implemented in witnet-rust
+      // {
+      //   name: 'base',
+      //   optional: true,
+      //   type: MirArgumentType.Integer,
+      // },
```
Comment (aesedepece) [inline src/structures.ts]: We can remove it altogether as there are no plans to support this.

**Review by aesedepece — CHANGES_REQUESTED** [review]

**Review by aesedepece — APPROVED** [review]
